# Generated by Django 4.0.5 on 2022-06-12 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=400)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.CharField(max_length=70)),
                ('category', models.CharField(choices=[('EE', 'Electrical Engineering'), ('CPE', 'Computer Engineering'), ('CS', 'Computer Science')], max_length=80)),
                ('video', models.FileField(null=True, upload_to='videos/')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('summary', models.TextField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.BooleanField(default=False)),
            ],
        ),
    ]
